#!/bin/bash

DIRNAME=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

export OMPSS_HOME=/apps/PM/ompss/git
export DLB_HOME=/apps/PM/dlb/latest/impi
export EXTRAE_HOME=/apps/BSCTOOLS/extrae/latest/impi_5_1_3_210
export PARAVER_HOME=/apps/BSCTOOLS/wxparaver/latest
export TEMANEJO_HOME=
export MPI_HOME=/apps/INTEL/2016.3.067/impi/5.1.3.210/intel64
export MPI_LIB_DIR=$MPI_HOME/lib
export MPI_INC_DIR=$MPI_HOME/include
export MPICC=mpiicc
export MPICXX=mpiicpc
export MPI_NATIVE_CC=I_MPI_CC
export MPI_NATIVE_CXX=I_MPI_CXX
export MPIRUN_COMMAND="mpirun"

# Note (vlopez); wxparaver needs glibcxx from gcc >= 5
module load gcc/5.1.0
module unload openmpi
module load impi/5.1.3.210
# Note (gmiranda): if you don't do this, mpiicc can't find icc. Fixme!
module load intel/16.0.0
export MKL_LIB_DIR=/opt/intel/mkl/lib/intel64/
export MKL_INC_DIR=/opt/intel/mkl/include/
export ATLAS_LIB_DIR=/apps/ATLAS/3.10.2/lib
export ATLAS_INC_DIR=/apps/ATLAS/3.10.2/include

ln -sf $DIRNAME/sched-job-smp_nord3 $DIRNAME/sched-job-smp
ln -sf $DIRNAME/sched-job-mpi_nord3 $DIRNAME/sched-job-mpi

# Python configuration (needed by Temanejo)
module load python
