#!/bin/bash

DIRNAME=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

export OMPSS_HOME=/apps/PM/ompss/16.06.3/
export EXTRAE_HOME=/apps/CEPBATOOLS/extrae/latest/default/64
export PARAVER_HOME=/apps/CEPBATOOLS/wxparaver/latest
export TEMANEJO_HOME=
export MPI_HOME=/opt/mpi/bullxmpi/1.1.11.1
export MPI_LIB_DIR=$MPI_HOME/lib
export MPI_INC_DIR=$MPI_HOME/include
export MPI_CC=mpicc
export MKL_LIB_DIR=/opt/compilers/intel/2016.3.067/mkl/lib/intel64/
export MKL_INC_DIR=/opt/compilers/intel/2016.3.067/mkl/include
export ATLAS_LIB_DIR=/gpfs/apps/NVIDIA/ATLAS/3.9.51/lib
export ATLAS_INC_DIR=/gpfs/apps/NVIDIA/ATLAS/3.9.51/include/

ln -sf $DIRNAME/sched-job-smp_nvidia $DIRNAME/sched-job-smp
ln -sf $DIRNAME/sched-job-mpi_nvidia $DIRNAME/sched-job-mpi

# Python configuration (needed by Temanejo)
module load python

# XML 2 used by Extrae:
export LD_LIBRARY_PATH=/apps/CEPBATOOLS/deps/libxml2/2.9.4/lib/:$LD_LIBRARY_PATH
